[package]
name = "cedar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb = "0.7.1"
openai-api-rs = "0.1.7"
rust-bert = { git = "https://github.com/guillaume-be/rust-bert", branch = "master" }
thiserror = "1.0.40"
tch = "0.12"
uuid = "1.3.2"
hnsw = "0.11.0"
rand_pcg = "0.3.1"
space = "0.18.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false
